<h1 align = "center"> Deep Neural Network </h1>

## Mount google drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## Import Libraries

In [ ]:
# work with data
import pandas as pd
import numpy as np

# train_test_split library
from sklearn.model_selection import train_test_split

# neural network
import tensorflow as tf

# pickle
import pickle

# import library to convert string to integer
from sklearn.preprocessing import LabelEncoder

# ignore warnings
import warnings
warnings.filterwarnings("ignore")

## Import Dataset

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dataset.csv')
df.head()

    N   P   K  temperature   humidity        ph    rainfall  crop
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

## Drop Columns

In [ ]:
# drop the result column from input data ('crop')
inputs = df.drop('crop', axis = 'columns')

# save the dropped column in separate variable
outputs = df[['crop']]

In [ ]:
# print input
inputs.head()

    N   P   K  temperature   humidity        ph    rainfall
0  90  42  43    20.879744  82.002744  6.502985  202.935536
1  85  58  41    21.770462  80.319644  7.038096  226.655537
2  60  55  44    23.004459  82.320763  7.840207  263.964248
3  74  35  40    26.491096  80.158363  6.980401  242.864034
4  78  42  42    20.130175  81.604873  7.628473  262.717340

In [ ]:
# print output
outputs.head()

   crop
0  rice
1  rice
2  rice
3  rice
4  rice

## Convert Strings

In [ ]:
#Encoding label (i.e string format) to integer for training and testing model
label_encoder = LabelEncoder()

In [ ]:
# create separate column for converted values
outputs['crop_converted'] = label_encoder.fit_transform(outputs['crop'])
outputs

        crop  crop_converted
0       rice              20
1       rice              20
2       rice              20
3       rice              20
4       rice              20
...      ...             ...
2195  coffee               5
2196  coffee               5
2197  coffee               5
2198  coffee               5
2199  coffee               5

[2200 rows x 2 columns]

In [ ]:
# ignore warning
pd.options.mode.chained_assignment = None

# drop string column
outputs_converted = outputs.drop(['crop'], axis = 'columns')
outputs_converted

      crop_converted
0                 20
1                 20
2                 20
3                 20
4                 20
...              ...
2195               5
2196               5
2197               5
2198               5
2199               5

[2200 rows x 1 columns]

In [ ]:
{index : label for index, label in enumerate(label_encoder.classes_)}

{0: 'apple',
 1: 'banana',
 2: 'blackgram',
 3: 'chickpea',
 4: 'coconut',
 5: 'coffee',
 6: 'cotton',
 7: 'grapes',
 8: 'jute',
 9: 'kidneybeans',
 10: 'lentil',
 11: 'maize',
 12: 'mango',
 13: 'mothbeans',
 14: 'mungbean',
 15: 'muskmelon',
 16: 'orange',
 17: 'papaya',
 18: 'pigeonpeas',
 19: 'pomegranate',
 20: 'rice',
 21: 'watermelon'}

## Split Dataset

In [ ]:
# split into 80% train and 20% test
X_train, X_test, y_train, y_test = train_test_split(inputs, outputs_converted, test_size = 0.2)

# Apply Neural Network

In [ ]:
a1 = tf.keras.Input(shape = (7, ))
a2 = tf.keras.layers.Dense(64, activation = 'relu')(a1)
a3 = tf.keras.layers.Dense(22, activation = 'softmax')(a2)

model = tf.keras.Model(a1,a3)

model.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = 'accuracy')

result = model.fit(X_train, y_train, validation_split = 0.2, batch_size = 128, epochs = 100)

Epoch 1/100
11/11 [==============================] - 1s 24ms/step - loss: 36.3325 - accuracy: 0.0760 - val_loss: 25.5931 - val_accuracy: 0.0909
Epoch 2/100
11/11 [==============================] - 0s 6ms/step - loss: 20.2494 - accuracy: 0.0987 - val_loss: 13.4087 - val_accuracy: 0.1449
Epoch 3/100
11/11 [==============================] - 0s 6ms/step - loss: 11.4454 - accuracy: 0.1790 - val_loss: 8.7539 - val_accuracy: 0.2131
Epoch 4/100
11/11 [==============================] - 0s 5ms/step - loss: 7.3482 - accuracy: 0.2472 - val_loss: 5.1906 - val_accuracy: 0.2812
Epoch 5/100
11/11 [==============================] - 0s 7ms/step - loss: 4.6251 - accuracy: 0.2592 - val_loss: 3.2082 - val_accuracy: 0.2841
Epoch 6/100
11/11 [==============================] - 0s 6ms/step - loss: 2.8276 - accuracy: 0.3345 - val_loss: 2.2953 - val_accuracy: 0.3807
Epoch 7/100
11/11 [==============================] - 0s 5ms/step - loss: 2.0033 - accuracy: 0.4396 - val_loss: 1.5360 - val_accuracy: 0.5312
Epoch 8/100
11/11 [==============================] - 0s 7ms/step - loss: 1.4236 - accuracy: 0.5447 - val_loss: 1.1588 - val_accuracy: 0.5824
Epoch 9/100
11/11 [==============================] - 0s 7ms/step - loss: 1.0586 - accuracy: 0.6335 - val_loss: 0.9220 - val_accuracy: 0.6506
Epoch 10/100
11/11 [==============================] - 0s 5ms/step - loss: 0.8386 - accuracy: 0.6953 - val_loss: 0.7664 - val_accuracy: 0.7131
Epoch 11/100
11/11 [==============================] - 0s 7ms/step - loss: 0.7058 - accuracy: 0.7493 - val_loss: 0.6438 - val_accuracy: 0.7699
Epoch 12/100
11/11 [==============================] - 0s 5ms/step - loss: 0.6133 - accuracy: 0.7919 - val_loss: 0.5833 - val_accuracy: 0.7670
Epoch 13/100
11/11 [==============================] - 0s 5ms/step - loss: 0.5276 - accuracy: 0.8175 - val_loss: 0.5067 - val_accuracy: 0.7869
Epoch 14/100
11/11 [==============================] - 0s 7ms/step - loss: 0.4744 - accuracy: 0.8409 - val_loss: 0.4772 - val_accuracy: 0.8068
Epoch 15/100
11/11 [==============================] - 0s 6ms/step - loss: 0.4193 - accuracy: 0.8651 - val_loss: 0.4219 - val_accuracy: 0.8494
Epoch 16/100
11/11 [==============================] - 0s 6ms/step - loss: 0.3747 - accuracy: 0.8807 - val_loss: 0.3999 - val_accuracy: 0.8551
Epoch 17/100
11/11 [==============================] - 0s 7ms/step - loss: 0.3482 - accuracy: 0.8885 - val_loss: 0.3690 - val_accuracy: 0.8608
Epoch 18/100
11/11 [==============================] - 0s 8ms/step - loss: 0.3229 - accuracy: 0.8991 - val_loss: 0.3501 - val_accuracy: 0.8835
Epoch 19/100
11/11 [==============================] - 0s 7ms/step - loss: 0.3054 - accuracy: 0.9027 - val_loss: 0.3401 - val_accuracy: 0.8920
Epoch 20/100
11/11 [==============================] - 0s 6ms/step - loss: 0.2855 - accuracy: 0.9155 - val_loss: 0.3186 - val_accuracy: 0.8949
Epoch 21/100
11/11 [==============================] - 0s 6ms/step - loss: 0.2703 - accuracy: 0.9190 - val_loss: 0.3041 - val_accuracy: 0.9006
Epoch 22/100
11/11 [==============================] - 0s 7ms/step - loss: 0.2604 - accuracy: 0.9212 - val_loss: 0.2968 - val_accuracy: 0.8949
Epoch 23/100
11/11 [==============================] - 0s 6ms/step - loss: 0.2477 - accuracy: 0.9283 - val_loss: 0.2819 - val_accuracy: 0.9148
Epoch 24/100
11/11 [==============================] - 0s 5ms/step - loss: 0.2354 - accuracy: 0.9339 - val_loss: 0.2731 - val_accuracy: 0.9091
Epoch 25/100
11/11 [==============================] - 0s 5ms/step - loss: 0.2323 - accuracy: 0.9283 - val_loss: 0.2732 - val_accuracy: 0.9176
Epoch 26/100
11/11 [==============================] - 0s 6ms/step - loss: 0.2242 - accuracy: 0.9347 - val_loss: 0.2691 - val_accuracy: 0.9062
Epoch 27/100
11/11 [==============================] - 0s 5ms/step - loss: 0.2168 - accuracy: 0.9325 - val_loss: 0.2470 - val_accuracy: 0.9261
Epoch 28/100
11/11 [==============================] - 0s 8ms/step - loss: 0.2090 - accuracy: 0.9418 - val_loss: 0.2485 - val_accuracy: 0.9233
Epoch 29/100
11/11 [==============================] - 0s 6ms/step - loss: 0.1991 - accuracy: 0.9453 - val_loss: 0.2356 - val_accuracy: 0.9318
Epoch 30/100
11/11 [==============================] - 0s 6ms/step - loss: 0.1939 - accuracy: 0.9503 - val_loss: 0.2380 - val_accuracy: 0.9205
Epoch 31/100
11/11 [==============================] - 0s 6ms/step - loss: 0.1863 - accuracy: 0.9503 - val_loss: 0.2245 - val_accuracy: 0.9403
Epoch 32/100
11/11 [==============================] - 0s 7ms/step - loss: 0.1860 - accuracy: 0.9496 - val_loss: 0.2376 - val_accuracy: 0.9318
Epoch 33/100
11/11 [==============================] - 0s 6ms/step - loss: 0.1830 - accuracy: 0.9489 - val_loss: 0.2209 - val_accuracy: 0.9403
Epoch 34/100
11/11 [==============================] - 0s 7ms/step - loss: 0.1792 - accuracy: 0.9510 - val_loss: 0.2194 - val_accuracy: 0.9432
Epoch 35/100
11/11 [==============================] - 0s 7ms/step - loss: 0.1722 - accuracy: 0.9538 - val_loss: 0.2110 - val_accuracy: 0.9460
Epoch 36/100
11/11 [==============================] - 0s 7ms/step - loss: 0.1672 - accuracy: 0.9560 - val_loss: 0.2053 - val_accuracy: 0.9403
Epoch 37/100
11/11 [==============================] - 0s 5ms/step - loss: 0.1599 - accuracy: 0.9574 - val_loss: 0.2081 - val_accuracy: 0.9517
Epoch 38/100
11/11 [==============================] - 0s 7ms/step - loss: 0.1628 - accuracy: 0.9560 - val_loss: 0.1980 - val_accuracy: 0.9517
Epoch 39/100
11/11 [==============================] - 0s 5ms/step - loss: 0.1563 - accuracy: 0.9602 - val_loss: 0.2073 - val_accuracy: 0.9432
Epoch 40/100
11/11 [==============================] - 0s 7ms/step - loss: 0.1546 - accuracy: 0.9595 - val_loss: 0.1960 - val_accuracy: 0.9432
Epoch 41/100
11/11 [==============================] - 0s 6ms/step - loss: 0.1536 - accuracy: 0.9574 - val_loss: 0.1985 - val_accuracy: 0.9460
Epoch 42/100
11/11 [==============================] - 0s 7ms/step - loss: 0.1469 - accuracy: 0.9624 - val_loss: 0.1906 - val_accuracy: 0.9460
Epoch 43/100
11/11 [==============================] - 0s 8ms/step - loss: 0.1431 - accuracy: 0.9645 - val_loss: 0.1937 - val_accuracy: 0.9403
Epoch 44/100
11/11 [==============================] - 0s 7ms/step - loss: 0.1423 - accuracy: 0.9638 - val_loss: 0.1847 - val_accuracy: 0.9545
Epoch 45/100
11/11 [==============================] - 0s 7ms/step - loss: 0.1443 - accuracy: 0.9588 - val_loss: 0.1984 - val_accuracy: 0.9517
Epoch 46/100
11/11 [==============================] - 0s 10ms/step - loss: 0.1397 - accuracy: 0.9624 - val_loss: 0.1787 - val_accuracy: 0.9574
Epoch 47/100
11/11 [==============================] - 0s 12ms/step - loss: 0.1394 - accuracy: 0.9588 - val_loss: 0.1932 - val_accuracy: 0.9375
Epoch 48/100
11/11 [==============================] - 0s 8ms/step - loss: 0.1356 - accuracy: 0.9624 - val_loss: 0.1886 - val_accuracy: 0.9545
Epoch 49/100
11/11 [==============================] - 0s 9ms/step - loss: 0.1311 - accuracy: 0.9659 - val_loss: 0.1725 - val_accuracy: 0.9545
Epoch 50/100
11/11 [==============================] - 0s 9ms/step - loss: 0.1314 - accuracy: 0.9666 - val_loss: 0.1768 - val_accuracy: 0.9460
Epoch 51/100
11/11 [==============================] - 0s 8ms/step - loss: 0.1300 - accuracy: 0.9673 - val_loss: 0.1872 - val_accuracy: 0.9489
Epoch 52/100
11/11 [==============================] - 0s 7ms/step - loss: 0.1359 - accuracy: 0.9624 - val_loss: 0.1709 - val_accuracy: 0.9574
Epoch 53/100
11/11 [==============================] - 0s 6ms/step - loss: 0.1259 - accuracy: 0.9702 - val_loss: 0.1711 - val_accuracy: 0.9460
Epoch 54/100
11/11 [==============================] - 0s 6ms/step - loss: 0.1233 - accuracy: 0.9695 - val_loss: 0.1654 - val_accuracy: 0.9602
Epoch 55/100
11/11 [==============================] - 0s 7ms/step - loss: 0.1213 - accuracy: 0.9680 - val_loss: 0.1647 - val_accuracy: 0.9545
Epoch 56/100
11/11 [==============================] - 0s 6ms/step - loss: 0.1194 - accuracy: 0.9652 - val_loss: 0.1650 - val_accuracy: 0.9602
Epoch 57/100
11/11 [==============================] - 0s 7ms/step - loss: 0.1184 - accuracy: 0.9695 - val_loss: 0.1619 - val_accuracy: 0.9602
Epoch 58/100
11/11 [==============================] - 0s 6ms/step - loss: 0.1189 - accuracy: 0.9659 - val_loss: 0.1614 - val_accuracy: 0.9545
Epoch 59/100
11/11 [==============================] - 0s 7ms/step - loss: 0.1196 - accuracy: 0.9666 - val_loss: 0.1616 - val_accuracy: 0.9545
Epoch 60/100
11/11 [==============================] - 0s 7ms/step - loss: 0.1174 - accuracy: 0.9680 - val_loss: 0.1616 - val_accuracy: 0.9545
Epoch 61/100
11/11 [==============================] - 0s 8ms/step - loss: 0.1167 - accuracy: 0.9659 - val_loss: 0.1594 - val_accuracy: 0.9574
Epoch 62/100
11/11 [==============================] - 0s 8ms/step - loss: 0.1145 - accuracy: 0.9652 - val_loss: 0.1597 - val_accuracy: 0.9517
Epoch 63/100
11/11 [==============================] - 0s 5ms/step - loss: 0.1112 - accuracy: 0.9673 - val_loss: 0.1524 - val_accuracy: 0.9602
Epoch 64/100
11/11 [==============================] - 0s 6ms/step - loss: 0.1117 - accuracy: 0.9645 - val_loss: 0.1531 - val_accuracy: 0.9545
Epoch 65/100
11/11 [==============================] - 0s 7ms/step - loss: 0.1103 - accuracy: 0.9666 - val_loss: 0.1527 - val_accuracy: 0.9574
Epoch 66/100
11/11 [==============================] - 0s 5ms/step - loss: 0.1066 - accuracy: 0.9723 - val_loss: 0.1512 - val_accuracy: 0.9574
Epoch 67/100
11/11 [==============================] - 0s 5ms/step - loss: 0.1046 - accuracy: 0.9673 - val_loss: 0.1504 - val_accuracy: 0.9574
Epoch 68/100
11/11 [==============================] - 0s 6ms/step - loss: 0.1070 - accuracy: 0.9688 - val_loss: 0.1488 - val_accuracy: 0.9602
Epoch 69/100
11/11 [==============================] - 0s 6ms/step - loss: 0.1069 - accuracy: 0.9702 - val_loss: 0.1482 - val_accuracy: 0.9545
Epoch 70/100
11/11 [==============================] - 0s 7ms/step - loss: 0.1051 - accuracy: 0.9737 - val_loss: 0.1433 - val_accuracy: 0.9574
Epoch 71/100
11/11 [==============================] - 0s 5ms/step - loss: 0.1028 - accuracy: 0.9702 - val_loss: 0.1450 - val_accuracy: 0.9574
Epoch 72/100
11/11 [==============================] - 0s 6ms/step - loss: 0.1031 - accuracy: 0.9716 - val_loss: 0.1398 - val_accuracy: 0.9602
Epoch 73/100
11/11 [==============================] - 0s 6ms/step - loss: 0.1030 - accuracy: 0.9695 - val_loss: 0.1539 - val_accuracy: 0.9460
Epoch 74/100
11/11 [==============================] - 0s 7ms/step - loss: 0.0992 - accuracy: 0.9744 - val_loss: 0.1386 - val_accuracy: 0.9574
Epoch 75/100
11/11 [==============================] - 0s 7ms/step - loss: 0.1005 - accuracy: 0.9695 - val_loss: 0.1467 - val_accuracy: 0.9517
Epoch 76/100
11/11 [==============================] - 0s 5ms/step - loss: 0.1015 - accuracy: 0.9659 - val_loss: 0.1420 - val_accuracy: 0.9545
Epoch 77/100
11/11 [==============================] - 0s 5ms/step - loss: 0.0987 - accuracy: 0.9709 - val_loss: 0.1426 - val_accuracy: 0.9545
Epoch 78/100
11/11 [==============================] - 0s 7ms/step - loss: 0.0952 - accuracy: 0.9751 - val_loss: 0.1353 - val_accuracy: 0.9659
Epoch 79/100
11/11 [==============================] - 0s 6ms/step - loss: 0.0942 - accuracy: 0.9737 - val_loss: 0.1382 - val_accuracy: 0.9545
Epoch 80/100
11/11 [==============================] - 0s 4ms/step - loss: 0.0964 - accuracy: 0.9709 - val_loss: 0.1360 - val_accuracy: 0.9602
Epoch 81/100
11/11 [==============================] - 0s 5ms/step - loss: 0.0928 - accuracy: 0.9759 - val_loss: 0.1326 - val_accuracy: 0.9574
Epoch 82/100
11/11 [==============================] - 0s 6ms/step - loss: 0.0969 - accuracy: 0.9680 - val_loss: 0.1337 - val_accuracy: 0.9545
Epoch 83/100
11/11 [==============================] - 0s 7ms/step - loss: 0.0928 - accuracy: 0.9730 - val_loss: 0.1294 - val_accuracy: 0.9602
Epoch 84/100
11/11 [==============================] - 0s 7ms/step - loss: 0.0934 - accuracy: 0.9702 - val_loss: 0.1262 - val_accuracy: 0.9602
Epoch 85/100
11/11 [==============================] - 0s 6ms/step - loss: 0.0948 - accuracy: 0.9702 - val_loss: 0.1480 - val_accuracy: 0.9517
Epoch 86/100
11/11 [==============================] - 0s 6ms/step - loss: 0.0926 - accuracy: 0.9730 - val_loss: 0.1247 - val_accuracy: 0.9602
Epoch 87/100
11/11 [==============================] - 0s 5ms/step - loss: 0.0901 - accuracy: 0.9744 - val_loss: 0.1329 - val_accuracy: 0.9631
Epoch 88/100
11/11 [==============================] - 0s 6ms/step - loss: 0.0916 - accuracy: 0.9766 - val_loss: 0.1319 - val_accuracy: 0.9631
Epoch 89/100
11/11 [==============================] - 0s 5ms/step - loss: 0.0931 - accuracy: 0.9744 - val_loss: 0.1267 - val_accuracy: 0.9602
Epoch 90/100
11/11 [==============================] - 0s 7ms/step - loss: 0.0887 - accuracy: 0.9723 - val_loss: 0.1260 - val_accuracy: 0.9574
Epoch 91/100
11/11 [==============================] - 0s 6ms/step - loss: 0.0875 - accuracy: 0.9744 - val_loss: 0.1282 - val_accuracy: 0.9574
Epoch 92/100
11/11 [==============================] - 0s 6ms/step - loss: 0.0917 - accuracy: 0.9716 - val_loss: 0.1402 - val_accuracy: 0.9574
Epoch 93/100
11/11 [==============================] - 0s 5ms/step - loss: 0.0942 - accuracy: 0.9723 - val_loss: 0.1219 - val_accuracy: 0.9602
Epoch 94/100
11/11 [==============================] - 0s 5ms/step - loss: 0.0888 - accuracy: 0.9751 - val_loss: 0.1297 - val_accuracy: 0.9545
Epoch 95/100
11/11 [==============================] - 0s 5ms/step - loss: 0.0936 - accuracy: 0.9695 - val_loss: 0.1289 - val_accuracy: 0.9602
Epoch 96/100
11/11 [==============================] - 0s 5ms/step - loss: 0.0884 - accuracy: 0.9730 - val_loss: 0.1222 - val_accuracy: 0.9602
Epoch 97/100
11/11 [==============================] - 0s 7ms/step - loss: 0.0860 - accuracy: 0.9723 - val_loss: 0.1276 - val_accuracy: 0.9602
Epoch 98/100
11/11 [==============================] - 0s 5ms/step - loss: 0.0872 - accuracy: 0.9709 - val_loss: 0.1190 - val_accuracy: 0.9602
Epoch 99/100
11/11 [==============================] - 0s 5ms/step - loss: 0.0863 - accuracy: 0.9709 - val_loss: 0.1152 - val_accuracy: 0.9545
Epoch 100/100
11/11 [==============================] - 0s 7ms/step - loss: 0.0842 - accuracy: 0.9723 - val_loss: 0.1274 - val_accuracy: 0.9517

In [ ]:
_, accuracy = model.evaluate(X_test, y_test)
print("Accuracy of Deep Neural Network algorithm is = \033[1m", round(accuracy * 100.0, 2), "\033[0m%")

14/14 [==============================] - 0s 2ms/step - loss: 0.1408 - accuracy: 0.9477
Accuracy of Deep Neural Network algorithm is =  94.77 %

In [ ]:
with open('DNN_MODEL', 'wb') as f:
    pickle.dump(model, f)

INFO:tensorflow:Assets written to: ram://eb094313-3cfe-45d3-bdca-accadf5fe998/assets